### ISSUE TITLE
Remove `multiqc` and `software_versions.yml` from rnadeseq report

### ISSUE THREAD

**Issue by ggabernet** [qbic-pipelines/rnadeseq#171]
### Description of feature

We just discussed with @qbicStefanC that it might make sense to already remove the `MultiQC`RNAseq part from the rnadeseq report so that it can be run with data coming from other projects.

**Comment by ggabernet** [comment]
we just discussed with @WackerO that the multiqc results thing is already optional and that he will make the `software_versions.yml` from the RNAseq pipeline optional too (and add this to the test_no_multiqc profile too)

**Comment by qbicStefanC** [comment]
Just to make sure because the title of this issue is starting with "Remove...": I think it would be nice to have the workflow running with both options, either MultiQC and software versions from RNA-Seq pipeline included ("in-house projects") or both excluded ("projects from outside where Primary Bx analysis was not done with qbic or nf-core. Thanks.S

**Comment by WackerO** [comment]
Closed with #200
